name: Build and Publish NuGet (Public Feed)

on:
  workflow_dispatch:
  release:
    types: 
      - published

# Limiting workflow concurrency
concurrency: 
  # Grouping by workflow, triggering event and ref name.
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: false
  
jobs:
  # Building, testing and packing
  build-test-pack:
    uses: ./.github/workflows/build-and-pack-template.yml


  # Publishing
  publish:
    name: Publish to NuGet

    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      PACKAGE_DIR: 'packages'
      PACKAGE_SOURCE: 'https://api.nuget.org/v3/index.json'

    # Add a dependency to the build job
    needs: build-test-pack

    environment:
      name: nuget-public

    steps:
      # https://github.com/marketplace/actions/download-a-build-artifact
      - uses: actions/download-artifact@v4
        with:
          name: Packages
          path: ${{ env.PACKAGE_DIR }}

      - name: Publish NuGet Package
        run: > 
          dotnet nuget push "${{ env.PACKAGE_DIR }}*.nupkg"
          --source ${{ env.PACKAGE_SOURCE }}
          --api-key ${{ secrets.NUGET_APIKEY }}
          --skip-duplicate

    